services:
  # База данных PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: hapi-postgres
    restart: unless-stopped
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: >
      postgres 
      -c max_connections=${POSTGRES_MAX_CONNECTIONS}
      -c shared_buffers=${POSTGRES_SHARED_BUFFERS}
      -c work_mem=${POSTGRES_WORK_MEM}
      -c max_wal_size=${POSTGRES_MAX_WAL_SIZE}
      -c min_wal_size=${POSTGRES_MIN_WAL_SIZE}
    ports:
      - "5432:5432"

  # Сервер HAPI FHIR
  hapi-fhir:
    image: hapi-fhir-jpaserver-starter-hapi-fhir-jpaserver-start:latest
    container_name: hapi-fhir-server
    restart: unless-stopped
    depends_on:
      - db
    env_file: .env
    environment:
      # Маппинг переменных из env-файлов в переменные приложения
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver

      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect

      HAPI_FHIR_FHIR_VERSION: ${HAPI_FHIR_VERSION}
      HAPI_FHIR_BULK_EXPORT_ENABLED: ${HAPI_BULK_EXPORT_ENABLED}
      HAPI_FHIR_BATCH_JOBS_ENABLED: ${HAPI_BATCH_JOBS_ENABLED}
      HAPI_FHIR_BINARY_STORAGE_ENABLED: ${HAPI_BINARY_STORAGE_ENABLED}
      HAPI_FHIR_VALIDATION_ENABLED: ${HAPI_FHIR_VALIDATION_ENABLED}
      HAPI_FHIR_BINARY_STORAGE_MODULE: DATASTORE
      HAPI_FHIR_TARGET_DIRECTORY: ${HAPI_EXPORT_DIR}

      HAPI_FHIR_ALLOW_EXTERNAL_REFERENCES: ${HAPI_FHIR_ALLOW_EXTERNAL_REFERENCES}
      HAPI_FHIR_AUTO_CREATE_PLACEHOLDER_REFERENCES: ${HAPI_FHIR_AUTO_CREATE_PLACEHOLDER_REFERENCES}
      HAPI_FHIR_EXTERNAL_REFERENCES_ENABLED: ${HAPI_FHIR_EXTERNAL_REFERENCES_ENABLED}
      HAPI_FHIR_ALLOW_ID_AND_RESOURCETYPE_IN_UPSERT_URLS: ${HAPI_FHIR_ALLOW_ID_AND_RESOURCETYPE_IN_UPSERT_URLS}
      
      JAVA_OPTS: ${HAPI_JAVA_OPTS}
    ports:
      - "8080:8080"
    volumes:
      - ../data/fhir_export:${HAPI_EXPORT_DIR}

  # ClickHouse
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-oncology
    restart: unless-stopped
    env_file: .env 
    environment:
      # ClickHouse подхватит эти переменные для создания начальной БД и юзера
      - CLICKHOUSE_DB=${CLICKHOUSE_DB}
      - CLICKHOUSE_USER=${CLICKHOUSE_USER}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=${CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT}
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./clickhouse_data:/var/lib/clickhouse
      - ./clickhouse_init:/docker-entrypoint-initdb.d
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "localhost:8123/ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    

volumes:
  postgres_data: